server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000" # 🔹 Only allow frontend
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"

      routes:
        - id: apps-service
          uri: http://backend-service:8080 # 🔹 Ensure correct backend URL
          predicates:
            - Path=/apps/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers

        - id: preflight-cors
          uri: no://op
          predicates:
            - Method=OPTIONS
          filters:
            - SetResponseHeader=Access-Control-Allow-Origin, http://localhost:3000
            - SetResponseHeader=Access-Control-Allow-Methods, GET, POST, PUT, DELETE, OPTIONS
            - SetResponseHeader=Access-Control-Allow-Headers, "*"
            - SetResponseHeader=Access-Control-Allow-Credentials, "true"
            - SetStatus=200
